config/routes.rb
Movieorganizer::Application.routes.draw do

  # manually add a new movie
  get '/current_user/new_movie' => 'movies#new', as: :add_movie
  post 'movies/' => 'movies#create'
  get 'movies/' => 'movies#index'

  delete 'movies/:movie_id' => 'movies#destroy', as: :movie

  get 'movies/:movie_id/edit' => 'movies#edit', as: :edit_movie
  patch 'movies/:movie_id' => 'movies#update'

  #search with YouTube API to add new movie
  get 'search/' => 'movies#search', as: :search
  post 'search/' => 'movies#do_search'

  # This is more or less the bare min of the first screen of the app.
  # This shows the Login, and create new account.
  get '/home' => 'users#home'
  get 'users/index' => 'users#index'

  # New/Create pairs
  get 'users/new' => 'users#new', as: :new_user
  post 'users/' => 'users#create'

  # Wireframe of user login
  root 'sessions#new'
  post '/log_in' => 'sessions#create'
  delete '/log_out' => 'sessions#destroy', as: :log_out
  get '/log_in/current_user' => 'sessions#show', as: :show_user
  get '/current_user/watched_list' => 'sessions#watched_show', as: :show_watched
  patch '/current_user/watched/:movie_id' => 'movies#watched', as: :watched_movie

end

app/models/movie.rb
require 'youtube_it'
require 'imdb'

class Movie
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic
  field :title, type: String
  field :director, type: String
  field :release_date, type: String
  field :trailer, type: String
  field :comment, type: String
  field :review, type: String

  has_many :usermovies
end

# attr_reader :release

# def release=(val)
#   self.release_date = Date.strptime(val, "%m/%d/%Y") if val.present?
# end

app/models/user.rb
require 'bcrypt'

class User
  include Mongoid::Document
  field :username, type: String
  field :password_digest, type: String
  field :name, type: String
  
  has_many :usermovies  

  validates :username, presence: true, uniqueness: true
  validates :name, presence: true

attr_reader :password

def password=(new_password)
	self.password_digest = BCrypt::Password.create(new_password)
end

def authenticate(entered_password)
	if entered_password && BCrypt::Password.new(self.password_digest) == entered_password
		self
	else
		false
	end

end

end

app/models/usermovie.rb
class Usermovie
  include Mongoid::Document
  field :watch, type: Boolean
  field :onwatchlist, type: Boolean

  belongs_to :user 
  belongs_to :movie

end

app/models/youtube.rb
# require 'rubygems'
# require 'google/api_client'
# require 'trollop'

class Youtube
  include Mongoid::Document
end

# def youtube_search(search_terms)

# DEVELOPER_KEY = "AIzaSyBLCkee2mXNaiWFoK-bArwk00IezSrHiXo"
# YOUTUBE_API_SERVICE_NAME = "youtube"
# YOUTUBE_API_VERSION = "v3"

# 	opts = Trollop::options do
# 	  opt :q, search_terms, :type => String, :default => 'Google'
# 	  opt :maxResults, 'Max results', :type => :int, :default => 5
# 	end

# client = Google::APIClient.new(:key => DEVELOPER_KEY,
#                                :authorization => nil)
# youtube = client.discovered_api(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION)

# opts[:part] = 'id'
# search_response = client.execute!(
#   :api_method => youtube.search.list,
#   :parameters => opts
# )

# @videos = []

# 	case search_result.id.kind
# 	    when 'youtube#video'
# 	      videos.push("#{search_result.id.videoId}")
# 	end
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  include MoviesHelper
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.order('created_at DESC').all
  end

  def new
  	@movie = Movie.new
  end

  def search
    @movie = Movie.new
  end

  def do_search
    @movie = Movie.new
    search_terms =  params[:search][:terms] 
    client = YouTubeIt::Client.new(:dev_key => "AI39si7vE4lh5EcW-n_4g1r4D9sYeCJKMqV7AvKHfsaKkWIKR8ACKVY0qiCsV226DufNNpRP2jdxbBqPjeJ33GNM6_8rf50bOw")
    @results = client.videos_by(:query => search_terms + "trailer", :per_page => 5)

    i = Imdb::Search.new(search_terms)
    d = i.movies.first.id
    dir = Imdb::Movie.new(d)
    @director = dir.director
    @release_date = dir.release_date
    @title = dir.title

    render "search"
  end

  def edit
    @movie = Movie.find(params[:movie_id])
  end

  def update
    @movie = Movie.find(params[:movie_id])

    if @movie.update_attributes(params.require(:movie).permit(:title, :director, :release_date, :trailer))
      redirect_to show_user_path
    else
      render 'edit'
    end
  end

  def watched
    Usermovie.where(movie_id: params[:movie_id]).update(watch: true)
    redirect_to show_user_path
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @movie.destroy
    Usermovie.where(movie_id: params[:movie_id]).destroy
    redirect_to show_user_path
  end

  def create
    @movie = Movie.create(params.require(:movie).permit(:title, :director, :release_date, :trailer, :comment))
    new_entry = Usermovie.new
    new_entry.user = current_user
    new_entry.movie = @movie
    new_entry.watch = false
    new_entry.save
    if @movie.save
      redirect_to show_user_path
    else
      render 'new'
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		flash.clear
		@body_class = "home-image"
	end

	def show
		@current_user_list = current_user.usermovies
	end	

	def watched_show
		@current_user_list = current_user.usermovies
	end

	def create
		flash.clear

		begin
			user = User.find_by({username: params[:session][:username]})
		rescue
			flash[:error] = "Please try again!"
		end

		if user && user.authenticate(params[:session][:password])
			log_in(user)
			redirect_to movies_path
		else
			flash[:error] ||= "Pleas try again!"
			render 'new'
		end

	end

	def destroy
		log_out
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def home
  end

  def index
    @users = User.all
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.create(params.require(:user).permit(:name, :username, :password))
  	if @user.save
      log_in(@user)
  		redirect_to show_user_path
  	else
  		render 'new'
  	end
  end

  def login
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

include MoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

def embed(youtube_url)
  youtube_split = youtube_url.split('=')
  youtube_id = youtube_split.last
  content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
end

def search_embed(unique_id)
  youtube_id = unique_id
  content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")	
end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		cookies.permanent[:logged_in_id] = user.id 
		@current_user = user
	end

	def log_out
		cookies.delete(:logged_in_id)
	end

	def logged_in?
		cookies[:logged_in_id] ? true : false
	end

	def current_user
		if logged_in?
			@current_user ||= User.find(cookies[:logged_in_id])
		else
			nil
		end
	end

	def current_user=(user)
		@current_user = user
	end

	def show
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" >
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<ul class="nav navbar-nav navbar-center navbar-right">
 <li><a href="#">
<%= link_to  "The Reel", movies_path %>
</a></li>
 <li><a href="#">
<%= link_to "My Movie List", :show_user %>
</a></li>
 <li><a href="#">
<%= link_to "Watched it!", :show_watched %>
</a></li>
 <li><a href="#">
<%= link_to "Search/Add", :search %>
</a></li>
 <li><a href="#">
<%= link_to "Log out", log_out_path, method: :delete%>
</a></li>
</ul>
</div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movieorganizer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= @body_class %>">

<nav>
	<% if logged_in? %>
	<%= render partial: "layouts/menu" %>
	<% end %>
</nav>

<%= yield %>

</body>
</html>

app/views/movies/edit.html.erb
<div class="edit-header">
<h1>Edit this movie</h1>
</div>

<%= form_for @movie do |entry| %>

<div class="edit-container">
<div class="form-group">
<%= entry.label :title %> </br> <%= entry.text_field :title, :class => "form-control" %>
</div>
<div class="form-group">
<%= entry.label :director %> </br> <%= entry.text_field :director, :class => "form-control" %>
</div>
<div class="form-group">
<%= entry.label :release_date %> </br> <%= entry.text_field :release_date, :class => "form-control" %>
</div>
<%= entry.submit "Submit update!" %></br>
<%= link_to "Go back", show_user_path %>
</div>

<% end %>

app/views/movies/index.html.erb
<div class="reel-header">
<h1> The Reel</h1>
<p>What users are adding</p>
</div>


<% @movies.each do |movie| %>
<div class="panel panel-default">
  <div class="panel-body">	
	<h4> Title: <%= movie.title %> </h4>
	Director: <%= movie.director %></br>
	Release date: <%= movie.release_date %></br>
	<% if movie.comment != nil %>
	Comment: <%= movie.comment %>
	<% end %>
  </div>
  <div class="panel-footer">	
	<% if movie.trailer != nil %>
	<div class="embed-responsive embed-responsive-4by3">
	<%= embed(movie.trailer) %>
	</div></br></br>
	<% end %>
  </div>	
</div>
<% end %>

<%= link_to "Go to my list", :show_user %>

app/views/movies/new.html.erb
<div class="jumbotron">
<h1>Add a new movie</h1>
</div>

<%= form_for @movie  do |movie| %>

<div class="form-group">
<%= movie.label :title %> </br> <%= movie.text_field :title %>
</div>
<div class="form-group">
<%= movie.label :director %> </br> <%= movie.text_field :director %>
</div>
<div class="form-group">
<%= movie.label :release_date %> </br> <%= movie.text_field :release_date %>
</div>
<div class="form-group">
<%= movie.label :trailer %> </br> <%= movie.text_field :trailer %>
</div></br></br>

<%= movie.label :submit %> <%= movie.submit "Add movie!" %>
</form>
<% end %>

<%= link_to "Go back", show_user_path %>

app/views/movies/search.html.erb
<div class="search-header">
 <h1>Search for a trailer</h1>
</div>

<div class="search-area">
  <%= form_for(:search, url: search_path) do |search| %>

  <%= search.text_field :terms %>

  <%= search.submit "Search!" %>

<% end %>
</div>

<% if @results != nil %>
<% @results.videos.each do |r| %>

<div class="search-results">

<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href='#<%= r.unique_id.parameterize %>'>
          <h4 class="glyphicon glyphicon-plus"> Add trailer</h4>
		</a>
      </h4>
    </div>
    <div id='<%= r.unique_id.parameterize %>' class="panel-collapse collapse">
      <div class="panel-body">
    
		<%= form_for @movie  do |movie| %>
		<div class="container">
		  <div class="col-md-3">
			<div class="form-group">
			  <%= movie.label :title %> </br> 
				<% if @title != nil %>
		  		<%= movie.text_field :title, :value => @title, :class => "form-control" %>
			   <% end %>
			</div>
		  </div>
		  <div class="col-md-3">
			<div class="form-group">
			  <%= movie.label :director %> </br> 
				<% if @director != nil %>
				<%= movie.text_field :director, :value => @director, :class => "form-control" %>
			  <% end %>
			</div>
		  </div>
		  <div class="col-md-3">
			<div class="form-group">
			  <%= movie.label :release_date %> </br> 
				<% if @release_date != nil%>
				  <%= movie.text_field :release_date, :value => @release_date, :class => "form-control" %>
				<% end %>
			  </div>
			</div>
			<div class="col-md-3">
			  <div class="form-group">
				<%= movie.label :comment %> </br> <%= movie.text_field :comment, :class => "form-control" %>
			  </div>
			</div>
			<div class="form-group">
			  <%= movie.label :trailer, :class => "sr-only" %><%= movie.hidden_field :trailer, :value => r.unique_id %>
			</div>
		  </div>
		  <%= movie.submit "Add movie!" %>
		<% end %>
      </div>
    </div>
  </div>
</div>

<div class="embed-responsive embed-responsive-16by9">
  <%= search_embed(r.unique_id) %>
</div>
</div>

<% end %>
<% end %>

app/views/users/home.html.erb
<h1>Mise-en-trailer</h1>

<p>An easy way to manage the movies you want to see</p>

<% if logged_in? %>
<p>Welcome <%= current_user.name %> to MovieApp</p>
<% end %>
<button type="button" class="btn btn-default navbar-btn">
<%= link_to "Log in", :log_in %>
</button>
<button type="button" class="btn btn-default navbar-btn">
<%= link_to "Log out", log_out_path, method: :delete %>
</button></br>
<%= link_to "Make new account", :new_user %>

app/views/users/index.html.erb
<% @users.each do |user| %>

<%= user.username %></br>

<% end %></br></br>

app/views/users/new.html.erb
<div class="new-user-header">
  <h1>Glad you can join us!</h1>
</div>

<% @user.errors.messages.each do |k,v| %>

  <%= k %> : <%= v.join(",") %>

<% end %>

<%= form_for @user do |user| %>
  <div class="new-user-form-container">
	<div class="form-group">
	  <%= user.label :name %> </br> <%= user.text_field :name, :class => "form-control" %>
	</div>
	<div class="form-group">
	  <%= user.label :username %> </br> <%= user.text_field :username, :class => "form-control" %>
	</div>
	<div class="form-group">
	  <%= user.label :password %> </br> <%= user.password_field :password, :class => "form-control" %>
	</div>
	  <%= user.submit "Create account!", :class => "btn btn-primary" %></br>
	  <%= link_to "Go Back", root_path %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= current_user.username %>'s Movie List</h1></br>


	<% current_user.usermovies.all.each do |movie| %>

	<h4>Movie Title: <%= movie.movie[:title] %></h4>
	<p>Director: <%= movie.movie[:director] %></p> 
	<p>Release date: <%= movie.movie[:release_date] %></p>

	<% end %>

<%= link_to "Add new movie", :add_movie%></br>
<%= link_to "Search for a movie", :search_movie %></br>
<%= link_to "Go back", root_path %>